---
- name: Sync Zabbix template IDs from NetBox Custom Object rows back into NetBox
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    netbox_api_url: "{{ lookup('env','NETBOX_API') | default('', true) }}"
    netbox_token:   "{{ lookup('env','NETBOX_TOKEN') | default('', true) }}"
    nb_validate_certs: true
    co_collection_endpoint: "/api/plugins/netbox-custom-objects/zabbix-template-list/"
    name_field: "template_name"
    id_field:   "template_ID"
    zabbix_api_url:   "{{ lookup('env','ZABBIX_API_URL') | default('', true) }}"
    zabbix_api_token: "{{ lookup('env','ZABBIX_API_TOKEN') | default('', true) }}"
    zbx_validate_certs: true
    zbx_filter_key: "name"
    awx_api_url: "{{ lookup('env','AWX_API_URL') | default('', true) }}"
    awx_token:   "{{ lookup('env','AWX_API_TOKEN') | default('', true) }}"
    nb_page_size: 200
    out_json: "zbx_template_ids_from_nb.json"
    out_csv:  "zbx_template_ids_from_nb.csv"
  tasks:
    - name: Fail if required NetBox/Zabbix env vars are missing
      assert:
        that:
          - netbox_api_url | length > 0
          - netbox_token   | length > 0
          - zabbix_api_url | length > 0
          - zabbix_api_token | length > 0
        fail_msg: "Set NETBOX_API/NETBOX_TOKEN and ZABBIX_API_URL/ZABBIX_API_TOKEN in AWX env."
    - name: Normalize NetBox custom object collection URL
      set_fact:
        _co_base: >-
          {{
            (co_collection_endpoint.startswith('http')
              | ternary(co_collection_endpoint.rstrip('/'),
                        (netbox_api_url.rstrip('/') ~ '/' ~ co_collection_endpoint.lstrip('/')).rstrip('/')))
          }}
    - name: Get collection count
      uri:
        url: "{{ _co_base }}?limit=1"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        return_content: true
        validate_certs: "{{ nb_validate_certs }}"
      register: nb_count_res
      failed_when: nb_count_res.status not in [200]
    - name: Compute offsets
      set_fact:
        _nb_count: "{{ nb_count_res.json.count | default((nb_count_res.json.results | length) | default(0)) }}"
        _offsets: "{{ range(0, _nb_count|int, nb_page_size|int) | list }}"
    - name: Fetch all rows
      vars:
        _rows: []
      loop: "{{ _offsets if _nb_count|int > 0 else [0] }}"
      loop_control:
        label: "offset={{ item }}"
      uri:
        url: "{{ _co_base }}?limit={{ nb_page_size }}&offset={{ item }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        return_content: true
        validate_certs: "{{ nb_validate_certs }}"
      register: nb_pages
    - name: Accumulate NetBox rows
      set_fact:
        _nb_rows: >-
          {{
            (nb_pages.results
              | map(attribute='json')
              | map(attribute='results', default=[])
              | list
              | flatten)
          }}
    - name: Fallback if API returns unpaginated array
      when: _nb_rows | length == 0 and (nb_pages.results | length) > 0
      set_fact:
        _nb_rows: "{{ nb_pages.results[0].json if nb_pages.results[0].json is mapping else nb_pages.results[0].json }}"
    - name: Build list of template names from NetBox rows
      set_fact:
        _names: "{{ (_names | default([])) + [ item[name_field] | string ] }}"
      loop: "{{ _nb_rows }}"
      when: item[name_field] is defined and (item[name_field] | string | length) > 0
    - name: Fail if no names found in NetBox rows
      fail:
        msg: "No '{{ name_field }}' values found in NetBox custom object collection."
      when: (_names | default([])) | length == 0
    - nane: Query Zabbix template IDs (exact match on zbx_filter_key)
      uri:
        url: "{{ zabbix_api_url }}/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json-rpc"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "template.get"
          params:
            output: ["templateid","name","host"]
            filter: { "{{ zbx_filter_key }}": "{{ _names }}" }
          auth: "{{ zabbix_api_token }}"
          id: 1
        return_content: true
        validate_certs: "{{ zbx_validate_certs }}"
      register: zbx_templates_res
      failed_when: zbx_templates_res.status not in [200]
    - name: Build maps from Zabbix results
      set_fact:
        _zbx_rows: "{{ zbx_templates_res.json.result | default([]) }}"
        _map_by_name: "{{ dict((_zbx_rows | map(attribute='name') | list) | zip(_zbx_rows | map(attribute='templateid') | list)) }}"
        _map_by_host: "{{ dict((_zbx_rows | map(attribute='host') | list) | zip(_zbx_rows | map(attribute='templateid') | list)) }}"
        _use_map: "{{ _map_by_name if zbx_filter_key == 'name' else _map_by_host }}"
        _returned_keys: "{{ _zbx_rows | map(attribute=zbx_filter_key) | list }}"
        _missing_names: "{{ _names | difference(_returned_keys) }}"
    - name: Show name -> templateid map (from Zabbix)
      debug:
        var: _use_map
    - name: Warn for names not found in Zabbix
      when: _missing_names | length > 0
      debug:
        msg: "No exact Zabbix match for: {{ _missing_names | join(', ') }}"
    - name: Compute pending updates for NetBox
      set_fact:
        _updates: "{{ (_updates | default([])) + [ {
                   'id': item.id,
                   'nb_detail_url': _co_base ~ '/' ~ item.id ~ '/',
                   'name': item[name_field],
                   'new_id': _use_map[item[name_field]]
                 } ] }}"
      loop: "{{ _nb_rows }}"
      when:
        - item[name_field] is defined
        - _use_map.get(item[name_field]) is defined
        - (item[id_field] | default('')) | string != (_use_map[item[name_field]] | string)
    - name: PATCH template_ID for each changed row in NetBox
      when: (_updates | default([])) | length > 0
      loop: "{{ _updates }}"
      loop_control:
        label: "{{ item.name }}"
      uri:
        url: "{{ item.nb_detail_url }}"
        method: PATCH
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body: "{{ { id_field: item.new_id } }}"
        status_code: [200]
        return_content: true
        validate_certs: "{{ nb_validate_certs }}"
      register: nb_patch_results
    - name: Summary
      debug:
        msg:
          total_rows: "{{ _nb_rows | length }}"
          updated: "{{ (_updates | default([])) | length }}"
          missing_in_zabbix: "{{ _missing_names | length }}"
    - name: Write JSON (name -> id map)
      copy:
        dest: "{{ out_json }}"
        content: "{{ _use_map | to_nice_json }}"
      delegate_to: localhost
    - name: Write CSV from NetBox rows (name,existing_id,new_id)
      copy:
        dest: "{{ out_csv }}"
        content: |
          name,existing_id,new_id
          {% for r in _nb_rows %}
          {% set new = _use_map.get(r[name_field]) | default('') %}
          {{ r[name_field] }},{{ r[id_field] | default('') }},{{ new }}
          {% endfor %}
      delegate_to: localhost