# templates_sync.yml
---
- name: Sync Zabbix template IDs from NetBox Custom Object rows back into NetBox (cert checks OFF)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # -------- NetBox from AWX env --------
    netbox_api_url: "{{ lookup('env','NETBOX_API') | default('', true) }}"
    netbox_token:   "{{ lookup('env','NETBOX_TOKEN') | default('', true) }}"

    # Your Custom Object collection (correct plugin slug + trailing slash)
    co_collection_endpoint: "/api/plugins/custom-objects/zabbix-template-list/"

    # Field names in your Custom Object
    name_field: "template_name"
    id_field:   "template_id"

    # -------- Zabbix from AWX env (API token) --------
    zabbix_api_url:   "{{ lookup('env','ZABBIX_API_URL') | default('', true) }}"
    zabbix_api_token: "{{ lookup('env','ZABBIX_API_TOKEN') | default('', true) }}"
    # Use 'host' if your NetBox names are Zabbix technical keys instead of display names
    zbx_filter_key: "name"

    # -------- Outputs --------
    nb_page_size: 200
    out_json: "zbx_template_ids_from_nb.json"
    out_csv:  "zbx_template_ids_from_nb.csv"

  tasks:
    - name: Fail if required NetBox/Zabbix env vars are missing
      assert:
        that:
          - netbox_api_url | length > 0
          - netbox_token   | length > 0
          - zabbix_api_url | length > 0
          - zabbix_api_token | length > 0
        fail_msg: "Set NETBOX_API/NETBOX_TOKEN and ZABBIX_API_URL/ZABBIX_API_TOKEN in AWX env."

    - name: Normalize NetBox custom object collection URL
      set_fact:
        _co_base: >-
          {{
            (co_collection_endpoint.startswith('http')
              | ternary(co_collection_endpoint.rstrip('/'),
                        (netbox_api_url.rstrip('/') ~ '/' ~ co_collection_endpoint.lstrip('/')).rstrip('/')))
          }}

    - name: Build Zabbix API endpoint URL (dedupe any trailing api_jsonrpc.php)
      set_fact:
        _zbx_endpoint: "{{ (zabbix_api_url | trim
                              | regex_replace('(/api_jsonrpc\\.php)+/?$', '')
                              | regex_replace('/+$', '')) ~ '/api_jsonrpc.php' }}"

    # ---- NetBox: get total count, then page through collection ----
    - name: Get collection count (paged API)
      uri:
        url: "{{ _co_base }}?limit=1"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        return_content: true
        validate_certs: false
        status_code: [200]
      register: nb_count_res

    - name: Compute count
      set_fact:
        _nb_count: "{{ nb_count_res.json.count
                      | default((nb_count_res.json.results | length) | default(0)) }}"

    - name: Compute offsets
      set_fact:
        _offsets: "{{ range(0, (_nb_count | int), (nb_page_size | int)) | list }}"

    - name: Fetch all pages
      loop: "{{ _offsets if (_nb_count | int) > 0 else [0] }}"
      loop_control:
        label: "offset={{ item }}"
      uri:
        url: "{{ _co_base }}?limit={{ nb_page_size }}&offset={{ item }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        return_content: true
        validate_certs: false
        status_code: [200]
      register: nb_pages

    - name: Accumulate NetBox rows (paginated)
      set_fact:
        _nb_rows: >-
          {{
            (nb_pages.results
              | map(attribute='json')
              | map(attribute='results', default=[])
              | list
              | flatten)
          }}

    - name: Fallback for unpaginated responses
      when: _nb_rows | length == 0 and (nb_pages.results | length) > 0
      set_fact:
        _nb_rows: >-
          {{
            nb_pages.results[0].json
            if (nb_pages.results[0].json is sequence)
            else (nb_pages.results[0].json.results | default([]))
          }}

    - name: Extract template names from NetBox rows
      set_fact:
        _names: "{{ (_names | default([])) + [ (item[name_field] | string) ] }}"
      loop: "{{ _nb_rows }}"
      when: item[name_field] is defined and (item[name_field] | string | length) > 0

    - name: Fail if no names found in NetBox rows
      fail:
        msg: "No '{{ name_field }}' values found in NetBox custom object collection."
      when: (_names | default([])) | length == 0

    # ---- Zabbix: build filter and query template IDs (token auth) ----
    - name: Build Zabbix filter object (dynamic key)
      set_fact:
        _zbx_filter: "{{ { (zbx_filter_key): _names } }}"

    - name: Query Zabbix template IDs (exact match)
      uri:
        url: "{{ _zbx_endpoint }}"
        method: POST
        headers:
          Content-Type: "application/json-rpc"
          Authorization: "Bearer {{ zabbix_api_token }}"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "template.get"
          params:
            output: ["templateid","name","host"]
            filter: "{{ _zbx_filter }}"
          auth: "{{ zabbix_api_token }}"
          id: 1
        return_content: true
        validate_certs: false
        status_code: [200]
      register: zbx_templates_res

    - name: Build maps from Zabbix results
      set_fact:
        _zbx_rows: "{{ zbx_templates_res.json.result | default([]) }}"
        _map_by_name: "{{ dict((_zbx_rows | map(attribute='name') | list) | zip(_zbx_rows | map(attribute='templateid') | list)) }}"
        _map_by_host: "{{ dict((_zbx_rows | map(attribute='host') | list) | zip(_zbx_rows | map(attribute='templateid') | list)) }}"
        _use_map: "{{ _map_by_name if zbx_filter_key == 'name' else _map_by_host }}"
        _returned_keys: "{{ _zbx_rows | map(attribute=zbx_filter_key) | list }}"
        _missing_names: "{{ _names | difference(_returned_keys) }}"

    - name: Show name -> templateid map (from Zabbix)
      debug:
        var: _use_map

    - name: Warn for names not found in Zabbix
      when: _missing_names | length > 0
      debug:
        msg: "No exact Zabbix match for: {{ _missing_names | join(', ') }}"

    # ---- Prepare and send NetBox PATCHes where ID changed ----
    - name: Compute pending updates for NetBox
      set_fact:
        _updates: "{{ (_updates | default([])) + [ {
                   'id': item.id,
                   'nb_detail_url': (_co_base ~ '/' ~ item.id ~ '/'),
                   'name': item[name_field],
                   'new_id': _use_map[item[name_field]]
                 } ] }}"
      loop: "{{ _nb_rows }}"
      when:
        - item[name_field] is defined
        - _use_map.get(item[name_field]) is defined
        - (item[id_field] | default('')) | string != (_use_map[item[name_field]] | string)

    - name: PATCH template_id for each changed row in NetBox
      when: (_updates | default([])) | length > 0
      loop: "{{ _updates }}"
      loop_control:
        label: "{{ item.name }}"
      uri:
        url: "{{ item.nb_detail_url }}"
        method: PATCH
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body: "{{ { id_field: item.new_id } }}"
        status_code: [200, 204]
        return_content: true
        validate_certs: false
      register: nb_patch_results

    - name: Summary
      debug:
        msg:
          total_rows: "{{ _nb_rows | length }}"
          updated: "{{ (_updates | default([])) | length }}"
          missing_in_zabbix: "{{ _missing_names | length }}"

    - name: Write JSON (name -> id map)
      copy:
        dest: "{{ out_json }}"
        content: "{{ _use_map | to_nice_json }}"
      delegate_to: localhost

    - name: Write CSV from NetBox rows (name,existing_id,new_id)
      copy:
        dest: "{{ out_csv }}"
        content: |
          name,existing_id,new_id
          {% for r in _nb_rows %}
          {% set new = _use_map.get(r[name_field]) | default('') %}
          {{ r[name_field] }},{{ r[id_field] | default('') }},{{ new }}
          {% endfor %}
      delegate_to: localhost
