# templates_sync.yml
---
- name: Sync Zabbix template IDs from NetBox Custom Object rows back into NetBox (cert checks OFF)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # -------- NetBox from AWX env --------
    netbox_api_url: "{{ lookup('env','NETBOX_API') | default('', true) }}"
    netbox_token:   "{{ lookup('env','NETBOX_TOKEN') | default('', true) }}"

    # Custom Object collection (correct plugin slug + trailing slash)
    co_collection_endpoint: "/api/plugins/custom-objects/zabbix-template-list/"

    # Field names in your Custom Object
    name_field: "template_name"
    id_field:   "template_id"

    # -------- Zabbix from AWX env (API token) --------
    zabbix_api_url:   "{{ lookup('env','ZABBIX_API_URL') | default('', true) }}"
    zabbix_api_token: "{{ lookup('env','ZABBIX_API_TOKEN') | default('', true) }}"
    # Use 'host' if your NetBox names are Zabbix technical keys instead of display names
    zbx_filter_key: "name"

    # -------- Outputs --------
    nb_page_size: 200
    out_json: "zbx_template_ids_from_nb.json"
    out_csv:  "zbx_template_ids_from_nb.csv"

  tasks:
    - name: Fail if required NetBox/Zabbix env vars are missing
      assert:
        that:
          - netbox_api_url | length > 0
          - netbox_token   | length > 0
          - zabbix_api_url | length > 0
          - zabbix_api_token | length > 0
        fail_msg: "Set NETBOX_API/NETBOX_TOKEN and ZABBIX_API_URL/ZABBIX_API_TOKEN in AWX env."

    - name: Normalize NetBox custom object collection URL
      set_fact:
        _co_base: >-
          {{
            (co_collection_endpoint.startswith('http')
              | ternary(co_collection_
