- hosts: all
  gather_facts: false
  vars:
    zbx_url: "{{ lookup('env', 'ZABBIX_URL') }}"
    zbx_user: "{{ lookup('env', 'ZABBIX_USER') }}"
    zbx_password: "{{ lookup('env', 'ZABBIX_PASSWORD') }}"
    remove_mode: "{{ ZBX_REMOVE_MODE | default('disable') }}"  # 'disable' or 'delete'
  tasks:
    - name: Disable host in Zabbix (soft removal)
      community.zabbix.zabbix_host:
        server_url: "{{ zbx_url }}"
        login_user: "{{ zbx_user }}"
        login_password: "{{ zbx_password }}"
        host: "{{ inventory_hostname }}"
        status: disabled
        state: present
      when: remove_mode == 'disable'

    - name: Delete host in Zabbix (hard removal)
      community.zabbix.zabbix_host:
        server_url: "{{ zbx_url }}"
        login_user: "{{ zbx_user }}"
        login_password: "{{ zbx_password }}"
        host: "{{ inventory_hostname }}"
        state: absent
      when: remove_mode == 'delete'

    - name: Mark Removed in NetBox
      netbox.netbox.netbox_device:
        netbox_url: "{{ lookup('env','NETBOX_API') }}"
        netbox_token: "{{ lookup('env','NETBOX_TOKEN') }}"
        validate_certs: "{{ (lookup('env','NETBOX_VERIFY') | default('true')) | bool }}"
        data:
          name: "{{ inventory_hostname }}"
          custom_fields:
            zbp_status: "Removed"
        state: present
      when: hostvars[inventory_hostname].is_vm | default(false) | bool == false
      delegate_to: localhost

    - name: Mark Removed in NetBox (VM)
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ lookup('env','NETBOX_API') }}"
        netbox_token: "{{ lookup('env','NETBOX_TOKEN') }}"
        validate_certs: "{{ (lookup('env','NETBOX_VERIFY') | default('true')) | bool }}"
        data:
          name: "{{ inventory_hostname }}"
          custom_fields:
            zbp_status: "Removed"
        state: present
      when: hostvars[inventory_hostname].is_vm | default(false)
      delegate_to: localhost
