---
# =============================================================================
# Zabbix Host Removal Playbook
# =============================================================================
# Description: Removes or disables hosts in Zabbix and updates NetBox status
#              accordingly. Deletes hosts with "decommissioning" status, disables
#              all other hosts, moves them to host group ID 75, and updates tags
#              (cmdb=archived, removes others).
#
# Author: Infrastructure Team
# Version: 1.0
# Last Updated: 2024
#
# Requirements:
#   - Ansible 2.9+
#   - netbox.netbox collection
#   - Zabbix API access with host management permissions
#   - NetBox API access with custom field write permissions
#
# Environment Variables Required:
#   - ZABBIX_API_TOKEN: Zabbix API authentication token
#   - NETBOX_TOKEN: NetBox API authentication token
#   - ZABBIX_VERIFY: SSL certificate verification (default: true)
#   - NETBOX_VERIFY: SSL certificate verification (default: false)
#
# Environment Variables Optional:
#   - ZABBIX_API_URL: Zabbix API endpoint (alternative: ZABBIX_URL, ZABBIX_HOST_URL)
#   - NETBOX_API: NetBox API endpoint (alternative: NETBOX_URL, NETBOX_HOST_URL)
#   - NB_REMOVE_STATUS: NetBox status to set after removal (default: 'removed')
#
# NetBox Custom Fields Used:
#   - zbp_status: Sync status (updated to NB_REMOVE_STATUS)
#   - zbp_sync_hint: Sync error details (cleared on successful removal)
#
# Usage:
#   # Remove hosts (deletes decommissioning, disables others)
#   ansible-playbook -i inventory zabbix_remove.yml
#
#   # Custom NetBox status after removal
#   NB_REMOVE_STATUS=decommissioned ansible-playbook -i inventory zabbix_remove.yml
#
# Features:
#   - Flexible URL resolution from multiple environment variable names
#   - Deletes hosts with "decommissioning" status
#   - Disables other hosts and moves them to host group ID 75
#   - Updates tags for disabled hosts (cmdb=archived, removes others)
#   - Updates NetBox custom fields with removal status
#   - Handles both devices and virtual machines
#   - Provides detailed operation summaries
#   - Validates host existence before attempting removal
#   - Confirms status changes for disable operations
# =============================================================================

- name: "Zabbix remove hosts (host-URL friendly, v5: default mode + set NetBox status)"
  hosts: all
  connection: local
  become: false
  gather_facts: false

  vars:
    # Tokens
    zbx_token: "{{ lookup('env','ZABBIX_API_TOKEN') }}"
    nb_token:  "{{ lookup('env','NETBOX_TOKEN') }}"
    # TLS verify toggles (optional envs; default true)
    zbx_validate_certs: "{{ (lookup('env','ZABBIX_VERIFY') | default('true')) | bool }}"
    nb_validate_certs:  "{{ (lookup('env','NETBOX_VERIFY')  | default('false')) | bool }}"
    # NetBox target status label/value to set after removal
    nb_target_status: "{{ lookup('env','NB_REMOVE_STATUS') | default('Removed', true) }}"

  tasks:
    # -------- Resolve endpoints from multiple possible env names --------
    - name: Resolve Zabbix base URL from env
      set_fact:
        _zbx_base_raw: >-
          {{
            lookup('env','ZABBIX_API_URL')
            | default(lookup('env','ZABBIX_URL'), true)
            | default(lookup('env','ZABBIX_HOST_URL'), true)
            | default('', true)
            | regex_replace('\s+$','')
          }}

    - name: Resolve NetBox base URL from env
      set_fact:
        _nb_base_raw: >-
          {{
            lookup('env','NETBOX_API')
            | default(lookup('env','NETBOX_URL'), true)
            | default(lookup('env','NETBOX_HOST_URL'), true)
            | default('', true)
            | regex_replace('\s+$','')
          }}

    - name: Canonicalise bases (strip query/fragment and trailing slash)
      set_fact:
        _zbx_base: '{{ _zbx_base_raw | regex_replace("[?#].*$","") | regex_replace("/+$","") }}'
        _nb_base:  '{{ _nb_base_raw  | regex_replace("[?#].*$","") | regex_replace("/+$","") }}'

    - name: Build effective endpoints
      set_fact:
        _zbx_api: '{{ (_zbx_base | regex_replace("/api_jsonrpc\.php$","", ignorecase=True)) ~ "/api_jsonrpc.php" }}'
        _nb_api:  '{{ (_nb_base  | regex_replace("/api$","",              ignorecase=True)) ~ "/api" }}'

    - name: Validate endpoints
      assert:
        that:
          - _zbx_base is search('^https?://')
          - _nb_base  is search('^https?://')
          - _zbx_api is search('api_jsonrpc\.php$')
          - _nb_api  is search('/api$')
        fail_msg: >-
          Missing/invalid endpoints.
          Zabbix base='{{ _zbx_base }}' api='{{ _zbx_api }}';
          NetBox base='{{ _nb_base }}' api='{{ _nb_api }}'.
          Expected ZABBIX_* to resolve to https://.../zabbix and NETBOX_* to https://... .

    - name: Show resolved endpoints
      debug:
        msg:
          zabbix_api: '{{ _zbx_api }}'
          netbox_base_for_module: '{{ _nb_base }}'

    # -------- Pick host name --------
    - name: Determine Zabbix host name to remove
      set_fact:
        _zbx_host: >-
          {{ hostvars[inventory_hostname].zabbix_name
             | default(hostvars[inventory_hostname].name | default(inventory_hostname)) }}

    # -------- Query Zabbix --------
    - name: Lookup host in Zabbix
      uri:
        url: '{{ _zbx_api }}'
        method: POST
        headers:
          Content-Type: 'application/json'
        body_format: json
        body:
          jsonrpc: '2.0'
          method: 'host.get'
          params:
            filter:
              host: ['{{ _zbx_host }}']
          auth: '{{ zbx_token }}'
          id: 1
        return_content: true
        validate_certs: '{{ zbx_validate_certs }}'
      register: zbx_get

    - name: Extract hostid or set empty if not found
      set_fact:
        _zbx_hostid: >-
          {{
            (zbx_get.json.result | first).hostid
            if (zbx_get.json.result is defined and 
                zbx_get.json.result | length > 0 and 
                (zbx_get.json.result | first).hostid is defined)
            else ''
          }}

    - name: Get device status from NetBox
      set_fact:
        _device_status: '{{ hostvars[inventory_hostname].status.value | default(hostvars[inventory_hostname].status) }}'

    - name: Determine action based on status
      set_fact:
        _action: '{{ "delete" if _device_status == "decommissioning" else "disable" }}'

    - name: Log host not found in Zabbix
      debug:
        msg: 'Host "{{ _zbx_host }}" not found in Zabbix; will mark as removed in NetBox only.'
      when: _zbx_hostid == ''

    - name: Set host not found flag
      set_fact:
        _host_not_found: true
      when: _zbx_hostid == ''

    # -------- Delete or disable based on status --------
    - name: Delete host in Zabbix (decommissioning status)
      when: _zbx_hostid is defined and _zbx_hostid != '' and _action == 'delete'
      uri:
        url: '{{ _zbx_api }}'
        method: POST
        headers:
          Content-Type: 'application/json'
        body_format: json
        body:
          jsonrpc: '2.0'
          method: 'host.delete'
          params: ['{{ _zbx_hostid }}']
          auth: '{{ zbx_token }}'
          id: 2
        validate_certs: '{{ zbx_validate_certs }}'
      register: zbx_delete

    - name: Disable host in Zabbix (other statuses)
      when: _zbx_hostid is defined and _zbx_hostid != '' and _action == 'disable'
      uri:
        url: '{{ _zbx_api }}'
        method: POST
        headers:
          Content-Type: 'application/json'
        body_format: json
        body:
          jsonrpc: '2.0'
          method: 'host.update'
          params:
            hostid: '{{ _zbx_hostid }}'
            status: 1     # 0=enabled, 1=disabled
          auth: '{{ zbx_token }}'
          id: 3
        validate_certs: '{{ zbx_validate_certs }}'
      register: zbx_disable

    - name: Change host group to ID 75 (other statuses)
      when: _zbx_hostid is defined and _zbx_hostid != '' and _action == 'disable'
      uri:
        url: '{{ _zbx_api }}'
        method: POST
        headers:
          Content-Type: 'application/json'
        body_format: json
        body:
          jsonrpc: '2.0'
          method: 'host.update'
          params:
            hostid: '{{ _zbx_hostid }}'
            groups:
              - groupid: '75'
          auth: '{{ zbx_token }}'
          id: 4
        validate_certs: '{{ zbx_validate_certs }}'
      register: zbx_group_change

    - name: Update tags - set cmdb to archived and remove others (other statuses)
      when: _zbx_hostid is defined and _zbx_hostid != '' and _action == 'disable'
      uri:
        url: '{{ _zbx_api }}'
        method: POST
        headers:
          Content-Type: 'application/json'
        body_format: json
        body:
          jsonrpc: '2.0'
          method: 'host.update'
          params:
            hostid: '{{ _zbx_hostid }}'
            tags:
              - tag: 'cmdb'
                value: 'archived'
          auth: '{{ zbx_token }}'
          id: 6
        validate_certs: '{{ zbx_validate_certs }}'
      register: zbx_tag_change

    - name: Re-read host to confirm Zabbix status (only when disabled)
      when: _action == 'disable' and _zbx_hostid is defined and _zbx_hostid != ''
      uri:
        url: '{{ _zbx_api }}'
        method: POST
        headers: { Content-Type: 'application/json' }
        body_format: json
        body:
          jsonrpc: '2.0'
          method: 'host.get'
          params:
            output: ['hostid','name','status']
            filter: { host: ['{{ _zbx_host }}'] }
          auth: '{{ zbx_token }}'
          id: 5
        validate_certs: '{{ zbx_validate_certs }}'
      register: zbx_verify

    - name: Show Zabbix status after action
      debug:
        msg: >-
          {%- if _host_not_found is defined and _host_not_found -%}
          host not found in Zabbix; will mark as removed in NetBox only
          {%- elif _action == 'delete' -%}
          requested=delete; API reply={{ zbx_delete.json.result | default({}) }}
          {%- else -%}
          requested=disable; status={{ (zbx_verify.json.result | first).status | default('unknown') }}
          {%- if zbx_group_change is defined -%}
          ; host group changed to ID 75
          {%- endif -%}
          {%- if zbx_tag_change is defined -%}
          ; tags updated (cmdb=archived, others removed)
          {%- endif -%}
          {%- endif -%}

    # -------- NetBox write-back: set zbp_status + clear hint --------
    - name: Build NetBox writeback payload
      set_fact:
        _cf_removed: >-
          {{
            (hostvars[inventory_hostname].custom_fields | default({}))
            | combine({'zbp_status': nb_target_status}, recursive=True)
            | combine({'zbp_sync_hint': ''},       recursive=True)
          }}

    - name: Writeback to NetBox device (if not a VM)
      when: not (hostvars[inventory_hostname].is_virtual | default(false))
      delegate_to: localhost
      netbox.netbox.netbox_device:
        netbox_url: '{{ _nb_base }}'
        netbox_token: '{{ nb_token }}'
        validate_certs: '{{ nb_validate_certs }}'
        data:
          name: '{{ hostvars[inventory_hostname].name | default(inventory_hostname) }}'
          custom_fields: '{{ _cf_removed }}'
        state: present

    - name: Writeback to NetBox VM (if virtual)
      when: hostvars[inventory_hostname].is_virtual | default(false)
      delegate_to: localhost
      netbox.netbox.netbox_virtual_machine:
        netbox_url: '{{ _nb_base }}'
        netbox_token: '{{ nb_token }}'
        validate_certs: '{{ nb_validate_certs }}'
        data:
          name: '{{ hostvars[inventory_hostname].name | default(inventory_hostname) }}'
          custom_fields: '{{ _cf_removed }}'
        state: present

    # -------- Job summary --------
    - name: Summary
      debug:
        msg:
          host: '{{ _zbx_host }}'
          device_status: '{{ _device_status }}'
          action_taken: >-
            {{ 'not found in Zabbix' if (_host_not_found is defined and _host_not_found) else _action }}
          nb_status_set: '{{ nb_target_status }}'
          zbx_status_after: >-
            {{ 'not found' if (_host_not_found is defined and _host_not_found) 
               else ((zbx_verify.json.result | first).status if (_action == 'disable') else 'n/a (deleted)') }}
          host_group_changed: >-
            {{ 'No (host not found)' if (_host_not_found is defined and _host_not_found) 
               else ('Yes (to ID 75)' if (zbx_group_change is defined and _action == 'disable') else 'No') }}
          tags_updated: >-
            {{ 'No (host not found)' if (_host_not_found is defined and _host_not_found) 
               else ('Yes (cmdb=archived, others removed)' if (zbx_tag_change is defined and _action == 'disable') else 'No') }}
