plugin: netbox.netbox.nb_inventory

config_context: false
strict: false

# Only hosts ready to sync
query_filters:
- cf_zbp_status: "Not Synced"

compose:
zbx_status: custom_fields.zbp_status

# Create a single, explicit status group
# (No keyed_groups; this works across all plugin versions)
groups:
status_ready: "{{ zbx_status == 'Not Synced' }}"