plugin: netbox.netbox.nb_inventory

config_context: false
strict: false

# Only hosts pending removal
query_filters:
- cf_zbp_status: "Remove Pending"

compose:
zbx_status: custom_fields.zbp_status
# Debug information
host_type: "{{ 'VM' if is_virtual else 'Device' }}"
host_name: "{{ name }}"
host_status: "{{ status.value | default(status) }}"

groups:
status_remove_pending: "{{ zbx_status == 'Remove Pending' }}"