plugin: netbox.netbox.nb_inventory

fetch_virtual_machines: true

# only objects explicitly marked for monitoring
query_filters:
  - cf_mon_req: "true"

# build the zabbix-shaped variables
compose:
  zbx_host_name: "{{ name }}"

  # Visible name: CF override else require description; else None (fail -> disabled)
  zbx_visible_name: >-
    {% if custom_fields is defined and custom_fields.zb_vname is defined and custom_fields.zb_vname %}
      {{ custom_fields.zb_vname }}
    {% elif description is defined and description|length > 0 %}
      {{ name }} - {{ description }}
    {% else %}
      {{ None }}
    {% endif %}

  # Interface IP (CF override else primary IPv4)
  zbx_interface_ip: >-
    {% if custom_fields is defined and custom_fields.zb_int_ip is defined and custom_fields.zb_int_ip %}
      {{ custom_fields.zb_int_ip }}
    {% elif primary_ip4 is defined and primary_ip4 %}
      {{ primary_ip4 }}
    {% else %}
      {{ None }}
    {% endif %}

  # Tags / placement
  zbx_env: "{{ custom_fields.zb_mon_env | default(None) }}"
  zbx_site: "{{ sites[0] | default(None) }}"
  zbx_os: "{{ platforms[0] | default(None) }}"
  zbx_proxy_id: "{{ custom_fields.zb_proxy_id | default(None) }}"
  zbx_group_id: "{{ custom_fields.zb_group_id | default(None) }}"
  zbx_sla_code: "{{ custom_fields.sla_report_code | default(None) }}"
  zbx_extra_template_ids: "{{ custom_fields.zb_extra_templates | default([]) }}"

  # --- Primary template & interface type ---
  # The NetBox inventory plugin doesn't expose platform.custom_fields,
  # so we map from platform slug -> template data (provided below in Source variables).
  zbx_primary_template_id: >-
    {{ (zbx_template_map.get(platforms[0] | default(''), {})).id | default(None) }}
  zbx_template_interface_id: >-
    {{ (zbx_template_map.get(platforms[0] | default(''), {})).int_id | default(None) }}

  # Enabled when everything (except extra templates) is present and NOT already synced
  zbx_enabled: >-
    {{
      (custom_fields.mon_req | default(false))
      and (zbx_visible_name is string)
      and (zbx_primary_template_id is not none and (zbx_primary_template_id|string)|length > 0)
      and (zbx_template_interface_id is not none and (zbx_template_interface_id|string)|length > 0)
      and (zbx_interface_ip is not none and (zbx_interface_ip|string)|length > 0)
      and (zbx_env is not none and (zbx_env|string)|length > 0)
      and (zbx_os is not none and (zbx_os|string)|length > 0)
      and (zbx_site is not none and (zbx_site|string)|length > 0)
      and (zbx_proxy_id is not none and (zbx_proxy_id|string)|length > 0)
      and (zbx_group_id is not none and (zbx_group_id|string)|length > 0)
      and (zbx_sla_code is not none and (zbx_sla_code|string)|length > 0)
    }}
