plugin: netbox.netbox.nb_inventory

config_context: false
strict: false

# MUST be a list, not a dict
query_filters:
  - status: active
  - cf_mon_req: true

compose:
  host_name: name
  visible_name: custom_fields.zbp_vname
  primary_template_id: custom_fields.zbp_pri_template_name_id
  primary_template: custom_fields.zbp_pri_template_name
  template_interface_id: custom_fields.zbp_pri_template_int_id
  template_interface: custom_fields.zbp_pri_template_int_name
  host_ip: >-
    {{ custom_fields.zbp_int_ip | default(primary_ip4.address | default('') | regex_replace('/\\d+$','')) }}
  extra_templates: custom_fields.zb_extra_templates
  environment: custom_fields.zb_mon_env
  os: platform.slug
  site: site.slug
  zbx_proxy_id: custom_fields.zbp_proxy_id
  zbx_group_id: custom_fields.zbp_group_id
  sla_code: custom_fields.zbp_sla_code
  nb_status: status.value

keyed_groups:
  - key: site
    prefix: site
    separator: "_"
  - key: zbx_group_id
    prefix: zbgroup
    separator: "_"
  - key: zbx_proxy_id
    prefix: zbproxy
    separator: "_"
