plugin: netbox.netbox.nb_inventory

config_context: false
strict: false

query_filters:
  - cf_zbp_status: "Remove Pending"

compose:
  host_name: name
  zbx_proxy_id: custom_fields.zbp_proxy_id
  # add anything else you need for the removal task
